[package]
name = "android-usbser"
version = "0.3.0"
authors = [
    "wuwbobo2021 <wuwbobo@outlook.com>",
    "Thomas Epperson <thomas.epperson@gmail.com>",
]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/uglyoldbob/android-usbser-rs"
readme = "README.md"
description = """
Android host driver for USB serial adapters, currently working with CDC-ACM devices.
"""
keywords = ["usb", "serial", "serialport", "uart", "android"]
categories = ["api-bindings", "hardware-support"]

[package.metadata.docs.rs]
default-target = "aarch64-linux-android"
targets = [
    "aarch64-linux-android",
    "x86_64-unknown-linux-gnu",
]

[dependencies]
nusb = { git = "https://github.com/uglyoldbob/nusb.git", rev = "694ed76" }
serialport = "4.9"

[lib]
name = "android_usbser"
path = "lib.rs"
