[package]
name = "android-usbser"
version = "0.2.3"
authors = ["wuwbobo2021 <wuwbobo@outlook.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wuwbobo2021/android-usbser-rs"
readme = "README.md"
description = """
Android host driver for USB serial adapters, currently working with CDC-ACM devices.
"""
keywords = ["usb", "serial", "serialport", "uart", "android"]
categories = ["api-bindings", "hardware-support"]

[package.metadata.docs.rs]
default-target = "aarch64-linux-android"
targets = [
    "aarch64-linux-android",
    "x86_64-unknown-linux-gnu",
]

[dependencies]
nusb = { git = "https://github.com/wuwbobo2021/nusb.git", rev = "f4ff489" }
serialport = "4.7"

[lib]
name = "android_usbser"
path = "lib.rs"
